---
title: "Untitled"
output: 
    html_document:
        df_print: paged
---

```{r, message=FALSE}
library(here)
library(arrow)
library(ensembldb)
library(tidyverse)
```

```{r}
unique_protein_entry_tbl = read_parquet(
    here('annotation/intermediates/gencode_34/gencode_34_unique_protein_entries.parquet')
) %>%
    select(ensembl_prot_id = ensembl_prot_ids, uniq_protein_seq_entry_no = entry_no) %>%
    mutate(ensembl_prot_id = str_split(ensembl_prot_id, '\\|')) %>%
    unnest(cols = c(ensembl_prot_id)) %>%
    # De-duplicate the proteins in the PAR Y region
    distinct(ensembl_prot_id, uniq_protein_seq_entry_no)

unique_protein_entry_tbl %>% head()
```

```{r}
uniparc_map_tbl = read_tsv(
    here('annotation/intermediates/gencode_34/gencode_34_uniparc_mapping.tsv.gz'),
    col_types = cols(
        original_prot_id = col_integer(),
        uniparc_id = col_character(),
        uniparc_checksum = col_character(),
        ensembl_prot_ids = col_character(),
        uniprot_ids = col_character(),
        refseq_prot_ids = col_character()
    )
) %>%
    rename(
        uniparc_crc64_checksum = uniparc_checksum,
        uniparc_xref_uniprot_ids = uniprot_ids,
        uniparc_xref_ensembl_prot_ids = ensembl_prot_ids,
        uniparc_xref_refseq_prot_ids = refseq_prot_ids
    )

uniparc_map_tbl %>% head()
```

```{r}
gencode_uniparc_tbl = unique_protein_entry_tbl %>%
    left_join(uniparc_map_tbl, by = c("uniq_protein_seq_entry_no" = "original_prot_id"))

nrow(gencode_uniparc_tbl)
```

```{r}
gencode_uniparc_tbl %>% head()
```

Some proteins don't exist on UniParc
```{r}
gencode_uniparc_tbl %>% filter(is.na(uniparc_id))
```

```{r}
edb = EnsDb("~/Box/Resources/EnsDb.Hsapiens.v100.sqlite")
listColumns(edb)
```

```{r}
tx_tbl = transcripts(
    edb,
    columns = c("tx_id_version", "gene_id_version", "gene_name", "symbol", "description"),
    return.type = 'DataFrame'
) %>%
    as_tibble() %>%
    extract(description, 'hgnc_id', 'Acc:(HGNC:\\d+)')

tx_tbl %>% head(10)
```

All gene_name is equal to symbol
```{r}
tx_tbl %>%
    filter(symbol != gene_name)
```

Obtain the GENCODE/Ensembl protein to transcript ID mapping:
```{r}
protein_tbl = proteins(edb, columns = c("tx_id_version", "protein_id")) %>%
    as_tibble() %>%
    rename(ensembl_prot_id_no_ver = protein_id, ensembl_tx_id = tx_id_version)

protein_tbl %>% head()
```

Query the built-in Ensembl to UniProt mapping
```
ensembl_prot_to_uniprot_tbl = proteins(
    edb, 
    columns = c("protein_id", "uniprot_id", "uniprot_db", "uniprot_mapping_type")
) %>%
    as_tibble() %>%
    rename(ensembl_prot_id_no_ver = protein_id)

ensembl_prot_to_uniprot_tbl %>% head()
```

Link proteins to transcripts
```{r}
gencode_uniparc_tbl.with_tx_id = gencode_uniparc_tbl %>%
    mutate(ensembl_prot_id_no_ver = str_remove(ensembl_prot_id, '\\.\\d+$')) %>%
    left_join(protein_tbl, by = "ensembl_prot_id_no_ver")

# Make sure all the proteins have the corresponding ensembl transcript id
gencode_uniparc_tbl.with_tx_id %>% filter(is.na(ensembl_tx_id))
```

Create the protein annotation table
```{r}
gencode_annotated_tbl = gencode_uniparc_tbl.with_tx_id %>%
    select(-ensembl_prot_id_no_ver) %>%
    left_join(
        tx_tbl %>%
            select(
                ensembl_tx_id = tx_id_version,
                symbol,
                ensembl_gene_id = gene_id_version,
                hgnc_id
            ),
        by = "ensembl_tx_id"
    ) %>%
    select(
        ensembl_prot_id, 
        ensembl_tx_id, 
        symbol,
        hgnc_id,
        ensembl_gene_id,
        uniq_protein_seq_entry_no, 
        everything()
    )

gencode_annotated_tbl %>% head()
```

Some protein entries don't have HGNC ID
```{r}
proteins_without_hgnc_id_tbl = gencode_annotated_tbl %>%
    filter(is.na(hgnc_id)) %>%
    select(ensembl_prot_id, symbol, ensembl_gene_id)

nrow(proteins_without_hgnc_id_tbl)
```

```{r}
proteins_without_hgnc_id_tbl %>% head()
```


## Export
```{r}
gencode_annotated_tbl %>% write_tsv('../tracked_results/gencode_34_annotation.tsv.gz')
proteins_without_hgnc_id_tbl %>% write_tsv('../tracked_results/gencode_34_proteins_without_hgnc_id.tsv.gz')
```


