---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r, message=FALSE}
library(SummarizedExperiment)
library(here)
library(tidyverse)
```

```{r}
DATA_ROOT = '~/Box/MyCPTAC/CPTAC_data_collection_v1'
```

```{r}
protein_pth = fs::path(DATA_ROOT, 'CPTAC3/GBM_discovery/proteome_mssm_per_gene_clean.v4.0.20200430.rds')

phospho_pth = fs::path(DATA_ROOT, 'CPTAC3/GBM_discovery/phosphoproteome_mssm_per_gene_clean.v4.0.20200430.rds')
phospho_loc_pth = fs::path(DATA_ROOT, 'CPTAC3/GBM_discovery/phosphoproteome_mssm_per_gene_clean.v4.0.20200430.tsv.peptide_location.tsv.gz')

acetyl_pth = fs::path(DATA_ROOT, 'CPTAC3/GBM_discovery/acetylome_mssm_per_gene_clean.v4.0.20200430.rds')
acetyl_loc_pth = fs::path(DATA_ROOT, 'CPTAC3/GBM_discovery/acetylome_mssm_per_gene_clean.v4.0.20200430.tsv.peptide_location.tsv.gz')
```

```{r}
protein_annotation_gr = read_rds(here(
    'annotation/refseq_20180629/tracked_results/refseq_20180629_human_only_unique_loci_GRanges.rds'
))
names(mcols(protein_annotation_gr))
```

## Protein
```{r}
raw_protein_se = readRDS(protein_pth)
```


Check if all the proteins are RefSeq
```{r}
prot_ids_not_in_refseq = setdiff(
    rowData(raw_protein_se)$refseq_id,
    protein_annotation_gr$refseq_prot_id
)

rowData(raw_protein_se)[prot_ids_not_in_refseq, ] %>%
    as_tibble()
```

```{r}
protein_row_tbl = rowData(raw_protein_se) %>%
    as_tibble(rownames = 'symbol')

# Check if the gene symbols are unique
protein_row_tbl %>% count(symbol, sort = TRUE) %>%
    filter(n > 1)
```

Add gene level annotation
```{r}
gene_annotation_tbl = protein_annotation_gr %>%
    as_tibble() %>%
    distinct(symbol, hgnc_id, entrez_gene_id, ensembl_gene_id)

protein_full_row_tbl = protein_row_tbl %>%
    select(symbol, refseq_prot_id = refseq_id) %>% 
    left_join(gene_annotation_tbl, by = "symbol")

protein_full_row_tbl %>% head()
```
Organize colData
```{r}
protein_col_tbl = colData(raw_protein_se) %>%
    as_tibble(rownames = 'case_id') %>%
    select(
        case_id,
        aliquot_id,
        tmt_experiment = tmt_plex, tmt_channel,
        sample_type = tumor_normal
    ) %>%
    mutate(
        preferred_sample_name = case_id,
        sample_type = case_when(
            sample_type == 'tumor' ~ 'Primary Tumor',
            sample_type == 'normal' ~ 'GTEx Normal',
            TRUE ~ NA_character_
        )
    )

protein_col_tbl %>% head()
```
```{r}
protein_se = raw_protein_se[protein_full_row_tbl$symbol, ]
rownames(protein_se) = protein_full_row_tbl$symbol
rowData(protein_se) = protein_full_row_tbl %>% column_to_rownames('symbol')
colData(protein_se) = protein_col_tbl %>% column_to_rownames('preferred_sample_name') %>% as('DataFrame')

metadata(protein_se) = list(
    cohort = 'CPTAC3 GBM discovery cohort',
    pipeline = 'PNNL'
)
```

```{r}
protein_se
```



## Phospho
```{r}
raw_phospho_se = readRDS(phospho_pth)

phospho_loc_tbl = read_tsv(
    phospho_loc_pth,
    col_types = cols(
        peptide_start = col_integer(), 
        peptide_end = col_integer()
    ))
```

```{r}
raw_phospho_row_tbl = rowData(raw_phospho_se) %>% 
    as_tibble(rownames = 'original_id') %>%
    select(original_id, symbol = gene, refseq_prot_id = refseq_id) %>%
    inner_join(phospho_loc_tbl, by = 'original_id')

raw_phospho_row_tbl %>% head()
```
```{r}
phospho_na_percent = rowSums(is.na(assay(raw_phospho_se[raw_phospho_row_tbl$original_id, ]))) / ncol(raw_phospho_se)
hist(phospho_na_percent)
```

```{r}
phospho_row_tbl = raw_phospho_row_tbl %>%
    bind_cols(tibble(na_percent = phospho_na_percent)) %>%
    filter(
        peptide_loc_valid,
        na_percent <= 0.8
    ) %>%
    arrange(symbol, phosphosites, na_percent) %>%
    mutate(
        unique_site_id = base::make.unique(
            str_c(symbol, refseq_prot_id, phosphosites, sep = ':'), 
            sep='.'
        )
    )

phospho_row_tbl %>% head()
```
Some sites have duplication
```{r}
phospho_row_tbl %>% 
    count(symbol, phosphosites, sort = TRUE) %>% 
    filter(n > 1)
```

Combine the RefSeq annotation
```{r}
protein_annotation_tbl = protein_annotation_gr %>%
    mcols() %>%
    as_tibble() %>%
    select(-symbol)
```

```{r}
phospho_row_full_tbl = phospho_row_tbl %>% 
    select(unique_site_id, original_id, refseq_prot_id, symbol, phosphosites, 
           peptide, peptide_start, peptide_end) %>%
    left_join(
        protein_annotation_tbl,
        by = 'refseq_prot_id'
    )

phospho_row_full_tbl %>% head()
```
Make sure the sample name order is the same
```{r}
identical(rownames(colData(raw_phospho_se)), protein_col_tbl$preferred_sample_name)
```

```{r}
phospho_se = raw_phospho_se[phospho_row_full_tbl$original_id, ]

rownames(phospho_se) = phospho_row_full_tbl$unique_site_id
rowData(phospho_se) = phospho_row_full_tbl %>% column_to_rownames('unique_site_id')
colData(phospho_se) = colData(protein_se)

metadata(phospho_se) = list(
    cohort = 'CPTAC3 GBM discovery cohort',
    pipeline = 'PNNL'
)
```

```{r}
phospho_se
```



## Acetyl
```{r}
raw_acetyl_se = readRDS(acetyl_pth)

acetyl_loc_tbl = read_tsv(
    acetyl_loc_pth,
    col_types = cols(
        peptide_start = col_integer(), 
        peptide_end = col_integer()
    ))
```

```{r}
raw_acetyl_row_tbl = rowData(raw_acetyl_se) %>% 
    as_tibble(rownames = 'original_id') %>%
    select(original_id, symbol = gene, refseq_prot_id = refseq_id) %>%
    inner_join(acetyl_loc_tbl, by = 'original_id')

raw_acetyl_row_tbl %>% head()
```
```{r}
acetyl_na_percent = rowSums(is.na(assay(raw_acetyl_se[raw_acetyl_row_tbl$original_id, ]))) / ncol(raw_acetyl_se)
hist(acetyl_na_percent)
```
```{r}
acetyl_row_tbl = raw_acetyl_row_tbl %>%
    bind_cols(tibble(na_percent = acetyl_na_percent)) %>%
    filter(
        peptide_loc_valid,
        na_percent <= 0.8
    ) %>%
    arrange(symbol, acetylsites, na_percent) %>%
    mutate(
        unique_site_id = base::make.unique(
            str_c(symbol, refseq_prot_id, acetylsites, sep = ':'), 
            sep='.'
        )
    )

acetyl_row_tbl %>% head()
```

Some sites have duplication
```{r}
acetyl_row_tbl %>% 
    count(symbol, acetylsites, sort = TRUE) %>% 
    filter(n > 1)
```


Combine the RefSeq annotation
```{r}
acetyl_row_full_tbl = acetyl_row_tbl %>% 
    select(unique_site_id, original_id, refseq_prot_id, symbol, acetylsites, 
           peptide, peptide_start, peptide_end) %>%
    left_join(
        protein_annotation_tbl,
        by = 'refseq_prot_id'
    )

acetyl_row_full_tbl %>% head()
```
Check if we can re-use the protein col data
```{r}
identical(rownames(colData(raw_acetyl_se)), protein_col_tbl$preferred_sample_name)
```

```{r}
acetyl_se = raw_acetyl_se[acetyl_row_full_tbl$original_id, ]

rownames(acetyl_se) = acetyl_row_full_tbl$unique_site_id
rowData(acetyl_se) = acetyl_row_full_tbl %>% column_to_rownames('unique_site_id')
colData(acetyl_se) = colData(protein_se)

metadata(acetyl_se) = list(
    cohort = 'CPTAC3 GBM discovery cohort',
    pipeline = 'PNNL'
)
```

```{r}
acetyl_se
```



## Export
```{r}
protein_se %>% saveRDS(here('final_output/CPTAC3_GBM_discovery/CPTAC3_GBM_pnnl_proteome.rds'))
phospho_se %>% saveRDS(here('final_output/CPTAC3_GBM_discovery/CPTAC3_GBM_pnnl_phosphoproteome.rds'))
acetyl_se %>% saveRDS(here('final_output/CPTAC3_GBM_discovery/CPTAC3_GBM_pnnl_acetylome.rds'))
```