configfile: '../snakemake_config.local.json'


rule extract_refseq_ids:
    output: id_list='intermediates/refseq_20180629/refseq_protein_ids.list'
    input: 
        refseq_tsv='custom_sources/cptac3_refseq_20180629/refseq_20180629_human_only_unique_loci.tsv.gz'
    shell:
        "gzip -cd {input} | "
        'xsv select -d "\t" refseq_prot_id | '
        "tail -n+2 > {output}"


rule query_uniparc:
    output:
        uniparc_tsv='intermediates/refseq_20180629/refseq_uniparc_mapping.tsv'
    input:
        fa=f"{config['data_root']}/DCC/RefSeq_20180629/RefSeq.20180629_Human_ucsc_hg38_cpdbnr_mito_264contams.fasta.gz",
        id_list=rules.extract_refseq_ids.output.id_list
    params:
        uniparc_json_folder='intermediates/refseq_20180629/uniparc_jsons'
    shell:
        "mkdir -p {params.uniparc_json_folder}; "
        "python scripts/query_uniparc_by_seq.py "
        "{input.id_list} {input.fa} "
        "{output.uniparc_tsv} "
        "--json-dir {params.uniparc_json_folder}"